export const CALIFORNIA_CITIES = [
  "Anaheim",
  "Antioch",
  "Apple Valley",
  "Bakersfield",
  "Berkeley",
  "Burbank",
  "Carlsbad",
  "Chico",
  "Chula Vista",
  "Clovis",
  "Concord",
  "Corona",
  "Costa Mesa",
  "Daly City",
  "Downey",
  "El Cajon",
  "El Monte",
  "Elk Grove",
  "Escondido",
  "Fairfield",
  "Fontana",
  "Fremont",
  "Fresno",
  "Fullerton",
  "Garden Grove",
  "Glendale",
  "Hayward",
  "Huntington Beach",
  "Inglewood",
  "Irvine",
  "Lancaster",
  "Long Beach",
  "Los Angeles",
  "Menifee",
  "Merced",
  "Mission Viejo",
  "Modesto",
  "Moreno Valley",
  "Murrieta",
  "Norwalk",
  "Oakland",
  "Oceanside",
  "Ontario",
  "Orange",
  "Oxnard",
  "Palmdale",
  "Pasadena",
  "Pomona",
  "Rancho Cucamonga",
  "Redding",
  "Redlands",
  "Redondo Beach",
  "Rialto",
  "Richmond",
  "Riverside",
  "Roseville",
  "Sacramento",
  "Salinas",
  "San Bernardino",
  "San Buenaventura",
  "San Diego",
  "San Francisco",
  "San Jose",
  "San Leandro",
  "San Mateo",
  "Santa Ana",
  "Santa Barbara",
  "Santa Clara",
  "Santa Clarita",
  "Santa Maria",
  "Santa Monica",
  "Santa Rosa",
  "Simi Valley",
  "Stockton",
  "Sunnyvale",
  "Temecula",
  "Thousand Oaks",
  "Torrance",
  "Tracy",
  "Vallejo",
  "Victorville",
  "Visalia",
  "Vista",
  "West Covina",
] as const;

const CITY_LOOKUP = new Map(
  CALIFORNIA_CITIES.map((city) => [city.toLowerCase(), city])
);

export function normalizeCaliforniaCity(input: string): string | null {
  const cleaned = input.trim().replace(/\s+/g, " ").toLowerCase();
  return CITY_LOOKUP.get(cleaned) ?? null;
}

export function isCaliforniaCity(input: string): boolean {
  return normalizeCaliforniaCity(input) !== null;
}
